name: Backport to Dev

on:
  push:
    branches:
      - master  # O el nombre de su rama principal

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Check for changes
      id: check_changes
      run: |
        git diff --quiet origin/dev...origin/master || echo "::set-output name=has_changes::true"

    - name: Create backport branch
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git checkout -b backport-to-dev origin/dev
        git merge --no-ff origin/master -m "Backport: Merge master into dev"
        git push origin backport-to-dev

    - name: Create Pull Request
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        branch: backport-to-dev
        base: dev
        title: 'Backport: Merge master into dev'
        body: |
          Este PR backporta los cambios de master a dev.
          Por favor, revise los cambios y apruebe el PR si todo está correcto.
        draft: false
        labels: |
          backport
          needs review

    - name: Notify if no changes
      if: steps.check_changes.outputs.has_changes != 'true'
      run: |
        echo "No hay cambios para backport de master a dev."

    - name: Check for open PRs
      run: |
        pr_count=$(gh pr list --base dev --head backport-to-dev --json number --jq length)
        echo "Número de PRs abiertos de backport-to-dev a dev: $pr_count"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
