name: Backport from Master to Dev

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  backport-to-dev:
    name: Backport to Dev
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create backport branch
        run: |
          git fetch origin dev
          git checkout -b backport-to-dev origin/dev
          
          # Obtener el commit de merge
          MERGE_COMMIT_SHA=${{ github.event.pull_request.merge_commit_sha }}
          
          # Obtener los padres del commit de merge
          PARENT1=$(git rev-parse $MERGE_COMMIT_SHA^1)
          PARENT2=$(git rev-parse $MERGE_COMMIT_SHA^2)
          
          # Crear un nuevo commit con los cambios del merge
          git cherry-pick -m 1 $MERGE_COMMIT_SHA || {
            echo "Conflicto en cherry-pick. Resolviendo automáticamente..."
            git cherry-pick --abort
            git diff $PARENT1..$PARENT2 | git apply
            git add .
            git commit -m "Backport changes from $MERGE_COMMIT_SHA"
          }

      - name: Push changes
        run: git push origin backport-to-dev

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: backport-to-dev
          base: dev
          title: '[Backport] ${{ github.event.pull_request.title }}'
          body: |
            Backport of #${{ github.event.pull_request.number }} to dev branch.
            
            Original PR: ${{ github.event.pull_request.html_url }}
          labels: backport
