name: Backport to Dev
on:
  push:
    branches:
      - master
jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    
    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    
    - name: Get last commit author
      id: get_author
      run: |
        AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')
        AUTHOR_USERNAME=$(echo $AUTHOR | sed -n 's/.*<\(.*\)@.*/\1/p')
        echo "author=$AUTHOR" >> $GITHUB_OUTPUT
        echo "username=$AUTHOR_USERNAME" >> $GITHUB_OUTPUT
    
    - name: Check for differences
      id: check_diff
      run: |
        git fetch origin dev
        git diff --quiet origin/dev...origin/master || echo "has_changes=true" >> $GITHUB_OUTPUT
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        branch: backport-to-dev
        base: dev
        title: 'Backport: Merge master into dev'
        body: |
          Este PR backporta los cambios de master a dev.
          Por favor, revise los cambios y apruebe el PR si todo está correcto.
          Último autor del commit en master: ${{ steps.get_author.outputs.author }}
          
          ¿Hay cambios para mergear?: ${{ steps.check_diff.outputs.has_changes == 'true' && 'Sí' || 'No' }}
        draft: false
        labels: |
          backport
          needs review
        assignees: ${{ steps.get_author.outputs.username }}
    
    - name: Find Pull Request
      id: find_pr
      run: |
        PR_NUMBER=$(gh pr list --base dev --head backport-to-dev --json number --jq '.[0].number')
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    
    - name: Request review
      if: steps.find_pr.outputs.pr_number
      run: |
        gh pr review ${{ steps.find_pr.outputs.pr_number }} --request-reviews ${{ steps.get_author.outputs.username }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    
    - name: Notify status
      run: |
        if [ "${{ steps.check_diff.outputs.has_changes }}" == "true" ]; then
          echo "Se ha creado un PR para backport de master a dev."
        else
          echo "Se ha creado un PR, pero no hay cambios adicionales para backport de master a dev."
        fi
        echo "Número de PR creado: ${{ steps.find_pr.outputs.pr_number }}"
        echo "Estado actual de las ramas:"
        git show-branch master dev
