name: Backport to Dev (Protected Branch)
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create-backport-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Get last commit author
      id: get_author
      run: |
        AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')
        AUTHOR_USERNAME=$(echo $AUTHOR | sed -n 's/.*<\(.*\)@.*/\1/p')
        echo "author=$AUTHOR" >> $GITHUB_OUTPUT
        echo "username=$AUTHOR_USERNAME" >> $GITHUB_OUTPUT

    - name: Create or update backport branch
      run: |
        git fetch origin dev
        git checkout -B backport-to-dev origin/dev
        git merge origin/master --no-edit
        git push origin backport-to-dev --force

    - name: Check for differences
      id: check_diff
      run: |
        git diff --quiet origin/dev...backport-to-dev || echo "has_changes=true" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: steps.check_diff.outputs.has_changes == 'true'
      env:
        GH_TOKEN: ${{ secrets.PAT }}
      run: |
        PR_URL=$(gh pr create --base dev --head backport-to-dev --title "Backport: Merge master into dev" --body "Este PR backporta los cambios de master a dev.
        Por favor, revise los cambios y apruebe el PR si todo está correcto.

        Último autor del commit en master: ${{ steps.get_author.outputs.author }}" --label backport,"needs review")
        echo "PR creado: $PR_URL"

    - name: Notify status
      run: |
        if [ "${{ steps.check_diff.outputs.has_changes }}" == "true" ]; then
          echo "Se ha creado o actualizado un PR para backport de master a dev."
        else
          echo "No hay cambios adicionales para backport de master a dev."
        fi
        echo "Estado actual de la rama backport-to-dev:"
        git log -1 --oneline backport-to-dev
        echo "Diferencias entre master y backport-to-dev:"
        git diff --stat master...backport-to-dev
