name: Backport from Master to Dev

on:
  push:
    branches:
      - master
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - master

jobs:
  backport-to-dev:
    name: Backport to Dev
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create backport branch
        run: |
          git fetch origin dev
          git checkout -b backport-to-dev origin/dev
          git cherry-pick ${{ github.event.pull_request.merge_commit_sha }}

      - name: Push changes
        run: git push origin backport-to-dev

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: backport-to-dev
          base: dev
          title: '[Backport] ${{ github.event.pull_request.title }}'
          body: |
            Backport of #${{ github.event.pull_request.number }} to dev branch.
            
            Original PR: ${{ github.event.pull_request.html_url }}
          labels: backport
