name: Fast-forward Dev to Master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  fast-forward-dev:
    name: Fast-forward Dev to Master
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Fast-forward Dev to Master
        run: |
          git fetch origin master dev
          
          # Verificar si dev está detrás de master
          if git merge-base --is-ancestor origin/dev origin/master; then
            echo "Dev está detrás de master. Realizando fast-forward..."
            git checkout dev
            git merge --ff-only origin/master
            git push origin dev
          else
            echo "Dev no está detrás de master. No se puede realizar fast-forward."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Get PR author
        if: failure()
        id: get_author
        run: echo "pr_author=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT

      - name: Create Pull Request if needed
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          branch: update-dev-from-master
          base: dev
          title: 'Update Dev from Master'
          body: |
            No se pudo realizar un fast-forward de Dev a Master.
            Este PR contiene los cambios necesarios para actualizar Dev.
            
            Por favor, revise los cambios y resuelva cualquier conflicto si es necesario.
            
            Este PR fue creado automáticamente debido a un merge en master realizado por @${{ steps.get_author.outputs.pr_author }}.
          labels: update, needs review
          assignees: ${{ steps.get_author.outputs.pr_author }}

      - name: Notify status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Dev ha sido actualizado exitosamente con los cambios de Master."
          else
            echo "No se pudo actualizar Dev automáticamente. Se ha creado un PR para revisión manual y se ha asignado a @${{ steps.get_author.outputs.pr_author }}."
          fi

# name: Fast-forward Dev to Master

# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - master

# jobs:
#   fast-forward-dev:
#     name: Fast-forward Dev to Master
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           token: ${{ secrets.PAT }}

#       - name: Set up Git
#         run: |
#           git config user.name github-actions
#           git config user.email github-actions@github.com

#       - name: Fast-forward Dev to Master
#         run: |
#           git fetch origin master dev
          
#           # Verificar si dev está detrás de master
#           if git merge-base --is-ancestor origin/dev origin/master; then
#             echo "Dev está detrás de master. Realizando fast-forward..."
#             git checkout dev
#             git merge --ff-only origin/master
#             git push origin dev
#           else
#             echo "Dev no está detrás de master. No se puede realizar fast-forward."
#             exit 1
#           fi
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}

#       - name: Create Pull Request if needed
#         if: failure()
#         uses: peter-evans/create-pull-request@v5
#         with:
#           token: ${{ secrets.PAT }}
#           branch: update-dev-from-master
#           base: dev
#           title: 'Update Dev from Master'
#           body: |
#             No se pudo realizar un fast-forward de Dev a Master.
#             Este PR contiene los cambios necesarios para actualizar Dev.
            
#             Por favor, revise los cambios y resuelva cualquier conflicto si es necesario.
#           labels: update, needs review

#       - name: Notify status
#         if: always()
#         run: |
#           if [ ${{ job.status }} == 'success' ]; then
#             echo "Dev ha sido actualizado exitosamente con los cambios de Master."
#           else
#             echo "No se pudo actualizar Dev automáticamente. Se ha creado un PR para revisión manual."
#           fi
