name: Backport to Dev
on:
  push:
    branches:
      - master
jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    
    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    
    - name: Get last commit author
      id: get_author
      run: |
        AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')
        AUTHOR_USERNAME=$(echo $AUTHOR | sed -n 's/.*<\(.*\)@.*/\1/p')
        echo "author=$AUTHOR" >> $GITHUB_OUTPUT
        echo "username=$AUTHOR_USERNAME" >> $GITHUB_OUTPUT
    
    - name: Check for differences
      id: check_diff
      run: |
        git fetch origin dev
        git diff --quiet origin/dev...origin/master || echo "has_changes=true" >> $GITHUB_OUTPUT
    
    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        branch: backport-to-dev
        base: dev
        title: 'Backport: Merge master into dev'
        body: |
          Este PR backporta los cambios de master a dev.
          Por favor, revise los cambios y apruebe el PR si todo está correcto.
          Último autor del commit en master: ${{ steps.get_author.outputs.author }}
          
          ¿Hay cambios para mergear?: ${{ steps.check_diff.outputs.has_changes == 'true' && 'Sí' || 'No' }}
        draft: false
        labels: |
          backport
          needs review
        assignees: ${{ steps.get_author.outputs.username }}
    
    - name: PR Creation Status
      if: steps.create_pr.outputs.pull-request-number
      run: |
        echo "Pull Request creado con éxito."
        echo "Número de PR: ${{ steps.create_pr.outputs.pull-request-number }}"
        echo "URL del PR: ${{ steps.create_pr.outputs.pull-request-url }}"
      
    - name: PR Creation Failed
      if: steps.create_pr.outputs.pull-request-number == ''
      run: |
        echo "No se pudo crear un nuevo Pull Request."
        echo "Verificando si ya existe un PR..."
        
        existingPR=$(gh pr list --base dev --head backport-to-dev --json number,url --jq '.[0]')
        
        if [ -n "$existingPR" ]; then
          echo "Se encontró un PR existente:"
          echo "$existingPR" | jq .
        else
          echo "No se encontró ningún PR existente."
          echo "Detalles del intento de creación:"
          echo "Resultado: ${{ steps.create_pr.outputs.result }}"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    
    - name: List Open PRs
      run: |
        echo "Lista de PRs abiertos de backport-to-dev a dev:"
        gh pr list --base dev --head backport-to-dev --json number,title,url --jq '.[] | "PR #\(.number): \(.title) - \(.url)"'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    
    - name: Request review
      if: steps.create_pr.outputs.pull-request-number
      run: |
        gh pr review ${{ steps.create_pr.outputs.pull-request-number }} --request-reviews ${{ steps.get_author.outputs.username }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    
    - name: Notify status
      run: |
        if [ "${{ steps.check_diff.outputs.has_changes }}" == "true" ]; then
          echo "Se ha creado o actualizado un PR para backport de master a dev."
        else
          echo "Se ha verificado el estado del PR, pero no hay cambios adicionales para backport de master a dev."
        fi
        echo "Estado actual de las ramas:"
        git show-branch master dev
