name: Branch Cleanup After Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        run: echo "PR was merged, proceeding with branch cleanup check"

      - name: Delete branch if conditions are met
        if: github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          if [[ "$BRANCH_NAME" != "master" && "$BRANCH_NAME" != "dev" && "$BRANCH_NAME" != release* ]]; then
            echo "Deleting branch $BRANCH_NAME"
            gh api repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME -X DELETE
          else
            echo "Branch $BRANCH_NAME is protected and will not be deleted"
          fi

      - name: Notify status
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != "master" && "${{ github.event.pull_request.head.ref }}" != "dev" && "${{ github.event.pull_request.head.ref }}" != release* ]]; then
            echo "La rama ${{ github.event.pull_request.head.ref }} ha sido eliminada después del merge."
          else
            echo "La rama ${{ github.event.pull_request.head.ref }} es una rama protegida y no ha sido eliminada."
          fi
