name: Selective Backport to Dev
on:
  push:
    branches:
      - master
jobs:
  selective-backport:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Get commits to cherry-pick
      id: get_commits
      run: |
        commits=$(git log dev..master --pretty=format:"%H")
        echo "commits=$commits" >> $GITHUB_OUTPUT
        echo "Commits to cherry-pick: $commits"

    - name: Prepare backport branch
      run: |
        git fetch origin dev
        git checkout -b backport-to-dev origin/dev

    - name: Cherry-pick commits
      id: cherry_pick
      run: |
        success=true
        for commit in ${{ steps.get_commits.outputs.commits }}; do
          if ! git cherry-pick -x $commit; then
            echo "Cherry-pick failed for commit $commit"
            git cherry-pick --abort
            success=false
            break
          fi
        done
        echo "cherry_pick_success=$success" >> $GITHUB_OUTPUT

    - name: Create PR for successful cherry-pick
      if: steps.cherry_pick.outputs.cherry_pick_success == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        branch: backport-to-dev
        base: dev
        title: 'Backport: Cherry-pick from Master to Dev'
        body: |
          Este PR contiene commits cherry-picked de master a dev.
          Por favor, revise los cambios y apruebe el PR si todo está correcto.

          Commits incluidos:
          ${{ steps.get_commits.outputs.commits }}
        draft: false
        labels: |
          backport
          needs review

    - name: Create PR for manual backport
      if: steps.cherry_pick.outputs.cherry_pick_success == 'false'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        branch: manual-backport-to-dev
        base: dev
        title: 'Manual Backport: Master to Dev'
        body: |
          El cherry-pick automático falló. Por favor, realice el backport manualmente.

          Commits a considerar para el backport:
          ${{ steps.get_commits.outputs.commits }}
        draft: false
        labels: |
          backport
          needs review
          manual intervention

    - name: Provide backport status
      run: |
        if [ "${{ steps.cherry_pick.outputs.cherry_pick_success }}" == "true" ]; then
          echo "Se ha creado un PR con los commits cherry-picked de master a dev."
        else
          echo "No se pudieron cherry-pick todos los commits. Se ha creado un PR para backport manual."
        fi
        echo "Por favor, revise el PR creado y realice los ajustes necesarios."
